- Config:
    client_title: Runelite
    file_path_to_client: \.runelite\
    pc_profile: C:\Users\<YOURSELF>
    tesseract_path: C:\Program Files (x86)\Tesseract-OCR\
    enable_on_start: false
